### ISSUE TITLE
System.IO.DirectoryNotFoundException if there are folders in zip

### ISSUE THREAD

**Issue by Fantoom** [Tyrrrz/Onova#18]
I get System.IO.DirectoryNotFoundException error when trying to update (the zip contains folders like "Assets, lib , etc"), it shows 

`Could not find a part of the path 'C:\Users\myUser\AppData\Local\Onova\WallEngine\0.0.6\Assets'.`

**Comment by Tyrrrz** [comment]
Hi, can you tell me more about your setup? What's the stack trace and what `IPackageResolver`/`IPackageExtractor` are you using?

**Comment by Fantoom** [comment]
Sorry for so late answer, I saw the email from Github yesterday. I am using GithubPackageResolver and ZipPackageExtractor. Here is the code that causes that error.

        class UpdateManager
	 {
		   private readonly  IUpdateManager _updateManager = new Onova.UpdateManager(
		   new GithubPackageResolver("Fantoom", "WallEngine", "WallEngine-v*"), new 
                   ZipPackageExtractor());

		public async  void CheckForUpdate()
		{
			var check = await _updateManager.CheckForUpdatesAsync();

			// If there are none, notify user and return
			if (!check.CanUpdate)
			{
				System.Windows.Forms.MessageBox.Show("There are no updates available.");
				return;
			}
			else
			{
				System.Windows.Forms.MessageBox.Show("There are updates available.");
			}

			// Prepare the latest update
			await _updateManager.PrepareUpdateAsync(check.LastVersion);

			// Launch updater and exit
			_updateManager.LaunchUpdater(check.LastVersion);
			if (System.Diagnostics.Process.GetProcessesByName(System.IO.Path.GetFileNameWithoutExtension(System.Reflection.Assembly.GetEntryAssembly().Location)).Count() > 0)
			{
				System.Windows.MessageBox.Show("Closed to update", "WallEngine Updater", System.Windows.MessageBoxButton.OK);
				System.Diagnostics.Process.GetCurrentProcess().Kill();
			}
		}
	}
