### ISSUE TITLE
Use to override with git releases

### ISSUE THREAD

**Issue by lastlink** [Tyrrrz/Onova#19]
is it possible to download an update from git releases?

**Comment by Tyrrrz** [comment]
As opposed to nuget?

**Comment by Tyrrrz** [comment]
Or do you mean git releases as in GitHub releases? Then yes, you should use `GithubPackageResolver`.

**Comment by lastlink** [comment]
My understanding is that I could use this to prompt users or automate updating my .net application and I'd like to use git releases to do so.

**Comment by lastlink** [comment]
I see that the wiki has some info on getting started. https://github.com/Tyrrrz/Onova/wiki/Resolving-packages-from-GitHub-(GithubPackageResolver)

**Comment by Tyrrrz** [comment]
Yes that's correct
