### ISSUE TITLE
Use Onova with dotnet core application

### ISSUE THREAD

**Issue by joanlofe** [Tyrrrz/Onova#24]
Looking at the documentation it seems that Onova targets only desktop applications built with .NetStandard 2.0. We were wondering if there is any way you can use it to update ASP Net Core 2.0 web applications that use Kestrel as web server and, in case it is possible, how to do it.

Thanks in advance and best regards.

**Comment by Tyrrrz** [comment]
Hi.
The main use case is indeed updating desktop applications (both .NET Framework and .NET Core), but Onova doesn't really care what it's working with as long as it has an executable entry point. So if you're running your web application in a self-hosted Kestrel, it should theoretically work, although I haven't tested it.

**Comment by Tyrrrz** [comment]
Did this answer your question?

**Comment by joanlofe** [comment]
Could it work if the ASP .Net core application is installed as a Windows service?

**Comment by Tyrrrz** [comment]
I doubt it, but you can test it.

**Comment by joanlofe** [comment]
Thanks! I will post here the result of our tests, if successful.
