### ISSUE TITLE
"Delayed" restart

### ISSUE THREAD

**Issue by felipeleon73** [Tyrrrz/Onova#25]
First of all thank you so much!
I was looking for a framework to replace clickonce with dot net 3 and this is exactly what I was looking for ... Really a great job!
I used this code:

```
        public UpdateBarViewModel()
        {
            var appPath = Path.GetDirectoryName(Assembly.GetEntryAssembly().Location);
            var urlFile = Path.Combine(appPath, "RpositoryUrl");
            Url = File.Exists(urlFile) ? File.ReadAllText(urlFile) : "";
            if (!string.IsNullOrEmpty(Url))
            {
                var timer = new Timer(60000);
                timer.Elapsed += Timer_Elapsed;
                timer.Start();
            }
        }

        private async void Timer_Elapsed(object sender, ElapsedEventArgs e)
        {
            using (var manager = new UpdateManager(new LocalPackageResolver(Url, "*.zip"), new ZipPackageExtractor()))
            {
                var result = await manager.CheckForUpdatesAsync();
                if (result.CanUpdate)
                {
                    UpdateAvailable = true;
                    // Prepare an update by downloading and extracting the package
                    // (supports progress reporting and cancellation)
                    var progress = new Progress<double>(NotifyDownoading);
                    await manager.PrepareUpdateAsync(result.LastVersion, progress);

                    // Launch an executable that will apply the update
                    // (can be instructed to restart the application afterwards)
                    manager.LaunchUpdater(result.LastVersion, false);

                    // Terminate the running application so that the updater can overwrite files
                    //Environment.Exit(0);
                }
            }
        }

```

As you can see I don't want it to be closed independently ... I could lose a lot of user data.
If I set LaunchUpdater with restart = true, however, the application restarts even if the user is closed (let's say to go home :))
If the amount is false, I no longer have the possibility to restart it.
The behavior I would like is the following:
1-The new version is downloaded and installed
2-On gui I have a key that is activated with the words "a new version is present: Restart"
3-If the user clicks on the button the app restarts
4-if the user closes the app the new version is still installed but the app is not reopened

Currently I don't think I can get similar behavior.

**Comment by felipeleon73** [comment]
Sorry ... I entered the Italian version: D

**Comment by Tyrrrz** [comment]
Hi.

You can split up your "prepare update" and "apply update" phase. Basically, you'd want to check for updates and prepare them in the background and notify the user. Hook up your button to execute `LaunchUpdater` with `restartUpdatee = true` and hook up your normal exit with `LaunchUpdater` with `restartUpdatee = false`. You will need to store the update version in a variable somewhere and make sure the updater is not executed twice.

I actually do something like this in my own applications, e.g. [DiscordChatExporter](https://github.com/Tyrrrz/DiscordChatExporter), [YoutubeDownloader](https://github.com/Tyrrrz/YoutubeDownloader). Try downloading an older version from the releases.

**Comment by felipeleon73** [comment]
I took a look at the code at https://github.com/Tyrrrz/DiscordChatExporter/blob/master/DiscordChatExporter.Gui/Services/UpdateService.cs and its uses. Perfect. works like a charm.

**Comment by Tyrrrz** [comment]
Glad you worked it out :)
