### ISSUE TITLE
wrong updatee path in wpf .net core 3.0

### ISSUE THREAD

**Issue by tensei** [Tyrrrz/Onova#26]
the launcher gets started with the wrong updatee path with wpf .net core 3.0. 
it's a self-contained .exe

```
12-Dez-2019 18:58:18.268> Onova Updater v2.4.5.0 started with args: [C:\Users\xxx\AppData\Local\Temp\.net\ApplicationName\gkl4m13w.04h\ApplicationName.dll, C:\Users\xxx\AppData\Local\Onova\ApplicationName\1.0.4, True, ].
12-Dez-2019 18:58:18.275> Waiting for all running updatee instances to exit...
12-Dez-2019 18:58:18.784> Copying package contents from storage to updatee's directory...
12-Dez-2019 18:58:18.842> Restarting updatee [C:\Users\xxx\AppData\Local\Temp\.net\ApplicationName\gkl4m13w.04h\ApplicationName.exe ]...
12-Dez-2019 18:58:18.909> Restarted as pid:40824.
12-Dez-2019 18:58:18.909> Deleting package contents from storage...
12-Dez-2019 18:58:18.919> Update completed successfully.```

**Comment by Tyrrrz** [comment]
Interesting. Technically the path is correct as that's where your app resides when you use self-contained. I don't even think it's possible to get the actual path of the self-contained bundle from within the launched assembly...

**Comment by tensei** [comment]
this works for getting the path to the .exe 

```csharp
var updatee = Path.Join(Directory.GetCurrentDirectory(),
    Assembly.GetExecutingAssembly().GetName().Name + ".exe");
```

**Comment by Tyrrrz** [comment]
You should be able to initialize `UpdateManager` with a custom `UpdateeFilePath`:

https://github.com/Tyrrrz/Onova/blob/master/Onova/Models/AssemblyMetadata.cs#L29-L34

**Comment by tensei** [comment]
:O totally missed that 

thank you for helping

**Comment by Tyrrrz** [comment]
It's okay :)
