### ISSUE TITLE
GithubPackageResolver: if "name" is null or empty or whitespace resolve "tag_name" instead

### ISSUE THREAD

**Issue by miakh** [Tyrrrz/Onova#32]
When I set new release and I let the "name" property empty or whitespace "tag_name" is used instead as a title of the realease. So my suggestion is that Onova GithubPackageResolver would try to search version pattern in "tag_name" if not found in "name".

**Comment by Tyrrrz** [comment]
Is it even possible for the api to return null/undefined `name`? I thought it always defaulted to `tag_name` at response level.

**Comment by miakh** [comment]
Sorry, not `null`, just empty or whitespace string. If that's the case then `name` gets replaced by `tag_name` on the GitHub website, but not on API level.

**Comment by Tyrrrz** [comment]
I see, okay. Open for a PR.
