### ISSUE TITLE
Does not Update on Windows Store App (WAP Dist) - APPXBUNDLE (.appxbundle)

### ISSUE THREAD

**Issue by fritzen** [Tyrrrz/Onova#34]
-  Works great on dev mode. 

- Works great on most Commons Windows Installers

**- Does not work on Microsoft Store App (WAP redist) - APPXBUNDLE (.appxbundle)**

**how to reproduce the problem**

- **just** create a Microsoft Store packaging project with Onova Test App

- After administrator permission App.Updater.exe cant apply files. Apparently a permission issue, even with admin elevation permission

**Comment by Tyrrrz** [comment]
Store manages the installation of its apps itself, so it's very likely it prevents Onova from tampering with it. Also I believe it allows auto-update as well, which would probably make use of Onova unnecessary for such scenarios.

**Comment by fritzen** [comment]
You're right. Yet, even if it worked, I really don't know if I would know if Microsoft's usage policies would allow the use of its update solution. However, the Microsoft Store certification process is very slow. This is a big problem for me.

**Comment by Tyrrrz** [comment]
I would say Store sucks in general.

**Comment by fritzen** [comment]
I agree with you. The biggest advantage of the store is the visibility of the app. However, after I had to wait 8 days for the approval of the App version, I need to rethink the advantages and disadvantages of continuing to use the Microsoft Store.

Microsoft does not make clear the prohibition on using own auto-update solution for a critical part of the application, such as a business DLL for example.

https://docs.microsoft.com/en-us/windows/uwp/packaging/self-install-package-updates

**Comment by Tyrrrz** [comment]
This article actually has some useful info: https://www.techmesto.com/windows-store-apps-installed-save-data/

Not sure if this is possible to automate though.

![image](https://user-images.githubusercontent.com/1935960/85411485-18c95100-b571-11ea-9e99-7665d196152b.png)

**Comment by fritzen** [comment]
it really won't be easy to reconcile Microsoft's update process with its own update process. thanks!

**Comment by Tyrrrz** [comment]
Yeah, unfortunately.
