### ISSUE TITLE
Any plan to update to the nuget package? 

### ISSUE THREAD

**Issue by westside** [Tyrrrz/Onova#36]
Thank you for your great project. 
It's really easy to use and simple. 

However, I wanted to use githubresolver, but fixed version is not published yet.
https://github.com/Tyrrrz/Onova/pull/33

Do you have any plan for it? 

If not, I would make a fork and publish it to my own nuget. 

Thank you.

**Comment by Tyrrrz** [comment]
Thanks for the reminder, I forgot about those changes. Will publish new version now.
