### ISSUE TITLE
Support for private Github-repos

### ISSUE THREAD

**Issue by derech1e** [Tyrrrz/Onova#38]
Hey, there is currently no support for private Github-Repositorys.
It is possible to add this feature?

Thank you in advance.

**Comment by Tyrrrz** [comment]
Hey. There is, you just need to pass in your own `HttpClient` that has the authentication header set.

**Comment by derech1e** [comment]
Okay. I've tested it, but it didn't worked. A 404 is displayed, when I try to update.

**Comment by Tyrrrz** [comment]
Hmmm, that may very well be true. If that's the case, it should probably be possible to change this line so that it uses `url` instead of `browser_url`:

https://github.com/Tyrrrz/Onova/blob/ef20bdb26386ac6bafaef4247586be79429c7a61/Onova/Services/GithubPackageResolver.cs#L101

Can you try it and see?

**Comment by derech1e** [comment]
So I changed the the line to this:

`var assetUrl = assetJson.GetProperty("url").GetString();`

and that works. But when it comes to the actual download it fails. 

This error arise:

```
System.IO.InvalidDataException: End of Central Directory record could not be found.

   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()

   at System.IO.Compression.ZipArchive.Init(Stream stream, ZipArchiveMode mode, Boolean leaveOpen)

   at System.IO.Compression.ZipArchive..ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen, Encoding entryNameEncoding)

   at System.IO.Compression.ZipFile.Open(String archiveFileName, ZipArchiveMode mode, Encoding entryNameEncoding)

   at Onova.Services.ZipPackageExtractor.ExtractPackageAsync(String sourceFilePath, String destDirPath, IProgress`1 progress, CancellationToken cancellationToken)

   at Onova.UpdateManager.PrepareUpdateAsync(Version version, IProgress`1 progress, CancellationToken cancellationToken)

   at ...
```


I think you need to define a special or new HttpClient here: https://github.com/Tyrrrz/Onova/blob/ef20bdb26386ac6bafaef4247586be79429c7a61/Onova/Internal/HttpClientEx.cs#L85

So for me it worked to add new headers here:
https://github.com/Tyrrrz/Onova/blob/ef20bdb26386ac6bafaef4247586be79429c7a61/Onova/Internal/HttpClientEx.cs#L29

I copy and pasted the method and added:

` client.DefaultRequestHeaders.Add("Authorization", "token TOKEN");`
`client.DefaultRequestHeaders.Add("Accept", "application/octet-stream");`

Then I upated the HttpClient: `using var response = await GetPrivateDownloadSingleton().GetAsync(requestUri, HttpCompletionOption.ResponseHeadersRead, cancellationToken);`

I tested that way and it worked. But I think that is not the best way to solve the problem. When you add the Accept Header here:
https://github.com/Tyrrrz/Onova/blob/ef20bdb26386ac6bafaef4247586be79429c7a61/Onova/Internal/HttpClientEx.cs#L29
it won't work, because he try to parse a string (json) as a octet-stream first before he actual download the ZIP.

**Comment by Tyrrrz** [comment]
In that case, the `Accept` header needs to be added here:

https://github.com/Tyrrrz/Onova/blob/ef20bdb26386ac6bafaef4247586be79429c7a61/Onova/Internal/HttpClientEx.cs#L85

Potentially setting it to `Accept: */*` if that works.

**Comment by derech1e** [comment]
I tested it and it works only this way:

```
var request = new HttpRequestMessage(HttpMethod.Get, requestUri);
request.Headers.Add("Accept", "application/octet-stream");

using var response = await client.SendAsync(request, HttpCompletionOption.ResponseHeadersRead, cancellationToken);
```

**Comment by Tyrrrz** [comment]
Can you make a PR with this?
