### ISSUE TITLE
Updater dont work after the last update

### ISSUE THREAD

**Issue by derech1e** [Tyrrrz/Onova#41]
Since your latest update the updater download the update, but not corretly install it. When i try to finalize the update and restart the application, it will download the update again. You broke something in the last patch...

**Comment by derech1e** [comment]
Did the last commit fix this problem?

**Comment by Tyrrrz** [comment]
Hi. There were no changes to that in the last version.

**Comment by derech1e** [comment]
Mhh, strange. Now it works.
