### ISSUE TITLE
My Onova-related projects generate too many system*.dlls in the bin directory

### ISSUE THREAD

**Issue by YueLu0116** [Tyrrrz/Onova#44]
- Issue description
In the generated bin\Release directory, there exist **16**  system*.dlls, such as System.Buffers.dll/System.Buffers.xml, System.Memory.dll/System.Memory.xml, System.ValueTuple.dll/System.ValueTuple.xml, etc.
- Possible reason
Refer to [why does my net standard nuget package trigger so many dependencies](https://stackoverflow.com/questions/47365136/why-does-my-net-standard-nuget-package-trigger-so-many-dependencies/47366401#47366401) and [Using .NET Standard with Full Framework .NET](https://weblog.west-wind.com/posts/2019/Feb/19/Using-NET-Standard-with-Full-Framework-NET#concise-example-using-libgit2sharp-in-markdown-monster), these redundant output dlls may be the result of that current version of Onova depends on .netframework v4.6.1 and .netstandard v2.0, and .netframework 4.6.1 is just partially .net standard 2.0 compliant. Update to .netframework 4.7.2 or higher may resolve this issue.

**Comment by Tyrrrz** [comment]
Yeah, you may be seeing this because you're on old .NET Framework version. Starting from v4.7.2 it should be fine.
Ideally, of course, moving to .NET 5 will help too. The .NET Standard targets will be phased out eventually across most libraries in the eventual future, in favor of .NET 5/6+.

**Comment by YueLu0116** [comment]
> Yeah, you may be seeing this because you're on old .NET Framework version. Starting from v4.7.2 it should be fine.
> Ideally, of course, moving to .NET 5 will help too. The .NET Standard targets will be phased out eventually across most libraries in the eventual future, in favor of .NET 5/6+.

Thanks for your reply.
My project has been already on .Net Framework **v4.8**  and 16 system-related dlls were generated. I checked Onova in NuGet packages management in vs-2019, and in the dependencies list, it said Onova depended on both .Net Framework v4.6.1 and .Net Core v2.0. Should Onova itself be rebuild under higher version of .Net Framework instead of my project to avoid system-related dlls?

**Comment by Tyrrrz** [comment]
Actually, because it has a .NET Framework v4.6.1 target, it shouldn't bring any System dependencies -- this is something that only happens with .NET Standard packages. I thought it might be because of [`System.Text.Json` dependency](https://www.nuget.org/packages/System.Text.Json/4.7.1) but that one also seems to have .NET Framework v4.6.1 target. So I'm not sure where the System dll's are coming from in the first place.

**Comment by YueLu0116** [comment]
Thanks for your advice. It seems I need to check all the packages' dependencies of my project.
By the way, as a newbie (my career began just two months ago), I really appreciate your contribution to the open source community. So much to learn from you :)

**Comment by Tyrrrz** [comment]
You're welcome 🙂
